// This file was generated by Prisma - updated 2026-05-25
import { defineConfig } from '@prisma/config';

const connectionString = process.env.DATABASE_URL;

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasource: {
    url: connectionString,
  },
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
});
